services:
  oracle:
    # See the 'docker' subdirectory for the content of this image.
    # Note that we are using the sha256 hash of the image to ensure integrity.
    image: docker.io/oasisprotocol/demo-rofl:latest@sha256:42c32ccfe0a0c84ac5969a1399e4658bed8e8d1517cc6b26cdce67439c66c910
    environment:
      # Address of the oracle contract deployed on Sapphire.
      - CONTRACT_ADDRESS=1234845aaB7b6CD88c7fAd9E9E1cf07638805b20
      # Ticker.
      - TICKER=ROSEUSDT
    volumes:
      - /run/rofl-appd.sock:/run/rofl-appd.sock
